`timescale 1ns / 1ps

module ddr3_controller_tb;

    // ============================================================
    // CLOCK AND RESET
    // ============================================================
    logic clk;
    logic reset;

    // ============================================================
    // REQUEST INTERFACE
    // ============================================================
    logic        request_valid;
    logic        request_write;
    logic [31:0] address;
    logic [31:0] write_data;

    logic        request_ready;
    logic [31:0] read_data;
    logic        read_data_valid;

    // ============================================================
    // DDR3 COMMAND SIGNALS
    // ============================================================
    logic activate_cmd;
    logic read_cmd;
    logic write_cmd;
    logic precharge_cmd;
    logic refresh_cmd;

    // ============================================================
    // TEST RESULT COUNTERS
    // ============================================================
    integer pass_count;
    integer fail_count;

    // Refresh verification counters
    integer refresh_count;
    integer expected_refresh_count;


  
    // DUT INSTANTIATION
    
    ddr3_controller_top dut (
        .clk             (clk),
        .reset           (reset),

        .request_valid   (request_valid),
        .request_write   (request_write),
        .address         (address),
        .write_data      (write_data),

        .request_ready   (request_ready),
        .read_data       (read_data),
        .read_data_valid (read_data_valid),

        .activate_cmd    (activate_cmd),
        .read_cmd        (read_cmd),
        .write_cmd       (write_cmd),
        .precharge_cmd   (precharge_cmd),
        .refresh_cmd     (refresh_cmd)
    );


    
    // CLOCK GENERATION
    // CLOCK PERIOD = 10 ns
 
    initial begin
        clk = 1'b0;
        forever #5 clk = ~clk;
    end

    // REFRESH COMMAND MONITOR
    // Counts every refresh command generated by the controller
 
    always @(posedge clk) begin
        if (refresh_cmd) begin
            refresh_count = refresh_count + 1;
            $display(
                "REFRESH COMMAND DETECTED at time = %0t ns",
                $time
            );
        end
    end

    // WRITE MEMORY TASK

    task automatic write_memory(
        input logic [31:0] wr_address,
        input logic [31:0] wr_data
    );
        begin

            // Wait until controller is ready
            while (!request_ready)
                @(posedge clk);

            // Apply write request
            @(negedge clk);
            request_valid = 1'b1;
            request_write = 1'b1;
            address       = wr_address;
            write_data    = wr_data;

            // Wait for one active clock edge
            @(posedge clk);

            // Wait until controller accepts the request
            while (request_ready)
                @(posedge clk);

            // Remove request
            @(negedge clk);
            request_valid = 1'b0;
            request_write = 1'b0;

            // Wait until write operation completes
            while (!request_ready)
                @(posedge clk);

            $display(
                "WRITE COMPLETE: Address=%h Data=%h",
                wr_address,
                wr_data
            );

        end
    endtask


   
    // READ MEMORY TASK
  
    task automatic read_memory(
        input logic [31:0] rd_address,
        input logic [31:0] expected_data
    );
        begin

            // Wait until controller is ready
            while (!request_ready)
                @(posedge clk);

            // Apply read request
            @(negedge clk);
            request_valid = 1'b1;
            request_write = 1'b0;
            address       = rd_address;

            // Wait for one active clock edge
            @(posedge clk);

            // Wait until controller accepts request
            while (request_ready)
                @(posedge clk);

            // Remove request
            @(negedge clk);
            request_valid = 1'b0;

            // Wait for valid read data
            @(posedge read_data_valid);

            // Compare read data with expected data
            if (read_data === expected_data) begin

                pass_count = pass_count + 1;

                $display(
                    "READ PASS: Address=%h Expected=%h Actual=%h",
                    rd_address,
                    expected_data,
                    read_data
                );

            end
            else begin

                fail_count = fail_count + 1;

                $display(
                    "READ FAIL: Address=%h Expected=%h Actual=%h",
                    rd_address,
                    expected_data,
                    read_data
                );

            end

            // Wait until read operation completes
            while (!request_ready)
                @(posedge clk);

        end
    endtask


  
    // MAIN TEST SEQUENCE

    initial begin

        // --------------------------------------------------------
        // INITIAL VALUES
        // --------------------------------------------------------
        reset         = 1'b1;
        request_valid = 1'b0;
        request_write = 1'b0;
        address       = 32'h0000_0000;
        write_data    = 32'h0000_0000;

        pass_count             = 0;
        fail_count             = 0;
        refresh_count          = 0;
        expected_refresh_count = 1;


     
        #20;
        reset = 1'b0;


        $display("========================================");
        $display("SIMPLIFIED DDR3 MEMORY CONTROLLER TEST");
        $display("========================================");


        write_memory(
            32'h0000_0001,
            32'h1234_5678
        );

        read_memory(
            32'h0000_0001,
            32'h1234_5678
        );

        write_memory(
            32'h0000_0002,
            32'hA5A5_5A5A
        );

        read_memory(
            32'h0000_0002,
            32'hA5A5_5A5A
        );

        write_memory(
            32'h0000_0003,
            32'hDEAD_BEEF
        );

        read_memory(
            32'h0000_0003,
            32'hDEAD_BEEF
        );

        // WAIT TO ALLOW REFRESH OPERATION
       
        #1500;


     
        $display("========================================");
        $display("REFRESH TEST RESULTS");
        $display("REFRESH COUNT = %0d", refresh_count);

        if (refresh_count >= expected_refresh_count) begin
            $display("REFRESH TEST PASSED");
        end
        else begin
            $display("REFRESH TEST FAILED");
            fail_count = fail_count + 1;
        end


        $display("========================================");
        $display("FINAL TEST RESULTS");
        $display("PASS COUNT = %0d", pass_count);
        $display("FAIL COUNT = %0d", fail_count);
        $display("========================================");

        if ((fail_count == 0) && (pass_count == 3))
            $display("ALL TESTS PASSED");
        else
            $display("SOME TESTS FAILED");


        #20;
        $finish;

    end

endmodule
